In [1]:
# Dependencies and Setup
import requests
import time
import pandas as pd
import numpy as np
from pprint import pprint
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.ticker as ticker
import sklearn.datasets as dta
import scipy.stats as st
from scipy.stats import sem
from scipy.stats import linregress
import seaborn as sns

# API Call for extracting the data

In [2]:
# Set the base URL
covid_url = 'https://api.opencovid.ca/timeseries?geo=pt&fill=false&version=true&pt_names=canonical&hr_names=hruid&fmt=json'
covid_confirmed_cases_response = requests.get(covid_url).json()
# Define an empty list to fetch the covid confirmed cases
covid_cases_data = []
# Print to logger
print("Beginning Data Retrieval     ")
for case in covid_confirmed_cases_response['data']['cases']:
    covid_cases_data.append({"Province": case['region'], "Date" : case['date'], "Cumulative confirmed cases": case['value'], "Confirmed cases per day": case['value_daily']})            
# Indicate that Data Loading is complete 
print("Data Retrieval Complete      ")

Beginning Data Retrieval
Data Retrieval Complete

In [3]:
covid_confirmed_cases_data_df = pd.DataFrame(covid_cases_data)
# Show Record Count
covid_confirmed_cases_data_df.head(3)

  Province        Date  Cumulative confirmed cases  Confirmed cases per day
0  Alberta  2020-03-05                           1                        1
1  Alberta  2020-03-06                           1                        0
2  Alberta  2020-03-07                           2                        1

In [4]:
# Set the API base URL
covid_url = 'https://api.opencovid.ca/timeseries?geo=pt&fill=false&version=true&pt_names=canonical&hr_names=hruid&fmt=json'
covid_deaths_response = requests.get(covid_url).json()
# Define an empty list to fetch the death data
covid_death_data = []
# Print to logger
print("Beginning Data Retrieval     ")
for case in covid_deaths_response['data']['deaths']:
    covid_death_data.append({"Province": case['region'], "Date" : case['date'], "Cumulative death cases": case['value'], "Deaths per day": case['value_daily']})            
# Indicate that Data Loading is complete 
print("Data Retrieval Complete      ")

Beginning Data Retrieval
Data Retrieval Complete

In [5]:
death_data_df = pd.DataFrame(covid_death_data)
death_data_df.head(3)

  Province        Date  Cumulative death cases  Deaths per day
0  Alberta  2020-03-08                       0               0
1  Alberta  2020-03-09                       0               0
2  Alberta  2020-03-10                       0               0

In [6]:
# Set the API base URL
covid_url = 'https://api.opencovid.ca/timeseries?geo=pt&fill=false&version=true&pt_names=canonical&hr_names=hruid&fmt=json'
covid_hospitalization_response = requests.get(covid_url).json()
# Define an empty list to fetch the death data
hospitalization_data = []
# Print to logger
print("Beginning Data Retrieval     ")
for case in covid_hospitalization_response['data']['hospitalizations']:
    hospitalization_data.append({"Province": case['region'], "Date" : case['date'], "Cumulative hospitalizations cases": case['value'], "Hospitalizations per day": case['value_daily']})            
# Indicate that Data Loading is complete 
print("Data Retrieval Complete      ")

Beginning Data Retrieval
Data Retrieval Complete

In [7]:
hospitalization_data_df = pd.DataFrame(hospitalization_data)
hospitalization_data_df.head(3)

,Province,Date,Cumulative hospitalizations cases,Hospitalizations per day
0,Alberta,2020-01-25,0,0
1,Alberta,2020-01-26,0,0
2,Alberta,2020-01-27,0,0

# Merging the small dataframes to make one big dataframe

In [8]:
# Mering the three DataFrames named as covid_confirmed_cases_data_df, death_data_df and hospitalization_data_df on columns Province and Date as they are common columns in all of the dataframes
covid_combined_df = pd.merge(covid_confirmed_cases_data_df, pd.merge(death_data_df, hospitalization_data_df, on=['Province', 'Date']), on=['Province', 'Date'])
covid_combined_df

,Province,Date,Cumulative confirmed cases,Confirmed cases per day,Cumulative death cases,Deaths per day,Cumulative hospitalizations cases,Hospitalizations per day
0,Alberta,2020-03-08,3,1,0,0,0,0
1,Alberta,2020-03-09,7,4,0,0,4,4
2,Alberta,2020-03-10,16,9,0,0,5,1
3,Alberta,2020-03-11,23,7,0,0,5,0
4,Alberta,2020-03-12,26,3,0,0,5,0
...,...,...,...,...,...,...,...,...
13321,Yukon,2022-11-01,5556,3,32,0,0,0
13322,Yukon,2022-11-02,5560,4,32,0,0,0
13323,Yukon,2022-11-03,5564,4,32,0,0,0
13324,Yukon,2022-11-04,5566,2,32,0,0,0
13325,Yukon,2022-11-05,5573,7,32,0,0,0

# Cleaning the dataframe for negative values, inf or any null values, sorting and adding some new columns

In [9]:
covid_combined_final_df = covid_combined_df[(covid_combined_df['Cumulative confirmed cases'] >= 0) & (covid_combined_df['Confirmed cases per day'] >= 0) & (covid_combined_df['Cumulative death cases'] >= 0) & (covid_combined_df['Deaths per day'] >= 0) & (covid_combined_df['Cumulative hospitalizations cases'] >= 0)& (covid_combined_df['Hospitalizations per day'] >= 0)]
covid_combined_final_df = covid_combined_final_df.dropna()
covid_combined_final_df.describe()

,Cumulative confirmed cases,Confirmed cases per day,Cumulative death cases,Deaths per day,Cumulative hospitalizations cases,Hospitalizations per day
count,1.071500e+04,10715.000000,10715.000000,10715.000000,10715.000000,10715.000000
mean,1.438428e+05,288.284274,1804.143070,2.885954,212.430611,4.398600
std,3.004667e+05,1013.980437,3678.114806,9.743512,423.960552,18.329983
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.275000e+02,0.000000,4.000000,0.000000,0.000000,0.000000
50%,6.919000e+03,6.000000,65.000000,0.000000,10.000000,0.000000
75%,1.368580e+05,176.500000,1774.000000,0.500000,273.000000,0.000000
max,1.621493e+06,19509.000000,17910.000000,133.000000,4190.000000,758.000000

In [10]:
covid_combined_final_df['Mortality rate'] = round(((covid_combined_final_df['Cumulative death cases'] / covid_combined_final_df['Cumulative confirmed cases']) * 100), 3)
covid_combined_final_df['Daily mortality rate'] = round(((covid_combined_final_df['Deaths per day'] / covid_combined_final_df['Confirmed cases per day']) * 100), 3)
covid_combined_final_df

,Province,Date,Cumulative confirmed cases,Confirmed cases per day,Cumulative death cases,Deaths per day,Cumulative hospitalizations cases,Hospitalizations per day,Mortality rate,Daily mortality rate
0,Alberta,2020-03-08,3,1,0,0,0,0,0.000,0.0
1,Alberta,2020-03-09,7,4,0,0,4,4,0.000,0.0
2,Alberta,2020-03-10,16,9,0,0,5,1,0.000,0.0
3,Alberta,2020-03-11,23,7,0,0,5,0,0.000,0.0
4,Alberta,2020-03-12,26,3,0,0,5,0,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...
13321,Yukon,2022-11-01,5556,3,32,0,0,0,0.576,0.0
13322,Yukon,2022-11-02,5560,4,32,0,0,0,0.576,0.0
13323,Yukon,2022-11-03,5564,4,32,0,0,0,0.575,0.0
13324,Yukon,2022-11-04,5566,2,32,0,0,0,0.575,0.0
13325,Yukon,2022-11-05,5573,7,32,0,0,0,0.574,0.0

In [11]:
# sort the DataFrame by date in ascending order as covid_combined_final_sorted
covid_combined_final_df['Date'] = pd.to_datetime(covid_combined_final_df['Date'])
covid_combined_final_sorted = covid_combined_final_df.sort_values(by='Date')

In [12]:
# fill missing values with zero
covid_combined_final_sorted_filled = covid_combined_final_sorted.fillna(value=0)
# remove inf and replace with zero in column 'A'
covid_combined_final_sorted_filled['Daily mortality rate'] = covid_combined_final_sorted_filled['Daily mortality rate'].replace([np.inf, -np.inf], 0)

In [13]:
covid_dataframe_df = covid_combined_final_sorted_filled
# Assumptions made recovered data/Cured data was not available in the API so we assumed to use the cumulative hospitalizations cases to calculate the cumulative active cases
covid_dataframe_df['Cumulative Active Cases'] = covid_dataframe_df['Cumulative confirmed cases'] - (covid_dataframe_df['Cumulative death cases'] + covid_dataframe_df['Cumulative hospitalizations cases'])
covid_dataframe_df['Active Cases per day'] = covid_dataframe_df['Confirmed cases per day'] - (covid_dataframe_df['Deaths per day'] + covid_dataframe_df['Hospitalizations per day'])
covid_dataframe_df.sample(3)

,Province,Date,Cumulative confirmed cases,Confirmed cases per day,Cumulative death cases,Deaths per day,Cumulative hospitalizations cases,Hospitalizations per day,Mortality rate,Daily mortality rate,Cumulative Active Cases,Active Cases per day
9710,Prince Edward Island,2021-05-17,192,1,0,0,0,0,0.000,0.0,192,1
13146,Yukon,2022-05-10,4757,5,25,0,0,0,0.526,0.0,4732,5
486,Alberta,2021-07-07,232314,49,2307,0,140,2,0.993,0.0,229867,47

# putting pandas Dataframe into csv format file

In [14]:
covid_dataframe_df.to_csv("Covid19_dataset1_project3.csv", index=False)

# Testing the dataframe

In [15]:
Active_cases_per_province = covid_dataframe_df.groupby('Province').max()[['Cumulative Active Cases', 'Date']].sort_values(['Cumulative Active Cases'], ascending = False).reset_index()
# Active_cases_per_province = Active_cases_per_province.iloc[0:5]
Active_cases_per_province_df = Active_cases_per_province[['Province', 'Cumulative Active Cases']]
Active_cases_per_province_df = Active_cases_per_province_df.set_index('Province')
Active_cases_per_province_df.head(13)

                           Cumulative Active Cases
Province
Ontario                                    1604500
Quebec                                     1320104
Alberta                                     626560
British Columbia                            394448
Manitoba                                    153387
Saskatchewan                                145617
New Brunswick                                83576
Nova Scotia                                  73053
Prince Edward Island                         53893
Newfoundland and Labrador                    52952
Northwest Territories                        11486
Yukon                                         5541
Nunavut                                       3524